# Generated by Django 5.0.7 on 2024-08-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_bid_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bid",
        ),
    ]
