# Generated by Django 5.0.7 on 2024-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_bid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=10,
            ),
        ),
    ]
